package errorcodes

const (
	InvalidRequestPayload                   = "Invalid request payload"
	CreateNewAuthorFailure                  = "Failed to create a new author"
	EmptyAuthorName                         = "Fill the author name"
	InvalidAuthorId                         = "Invalid Author ID"
	AuthorNotFound                          = "Author not found"
	InvalidBookId                           = "Invalid book ID"
	BookNotFound                            = "Book not found"
	FailedToUpdateBook                      = "Failed to update the book"
	InvalidGenreId                          = "Invalid genre ID"
	InvalidParamType                        = "Invalid paramType"
	AuthorQueryFailure                      = "Failed to query authors"
	AuthorDeletionFailure                   = "Failed to delete the author"
	BookDeletionFailure                     = "Failed to delete books"
	InvalidOffsetValue                      = "Invalid offset value"
	BookQueryFailure                        = "Failed to query books"
	FailedToRetrieveAuthor                  = "Failed to retrieve author"
	BookAlreadyCreated                      = "Book already created"
	FailedToRetrieveGenre                   = "Failed to retrieve genre"
	CreateNewBookFailure                    = "Failed to create a new book"
	GenreNotFound                           = "Genres not found"
	GenreQueryFailure                       = "Failed to query genres"
	CreateNewGenreFailure                   = "Failed to create a new genre"
	FailedToUpdateGenre                     = "Failed to update the genre"
	GenreDeletionFailure                    = "Failed to delete the genre"
	FailedToFindBooksWithGenre              = "Failed to find books with the genre"
	FailedToRemoveGenreAssociationFromBooks = "Failed to update book genre association"
	BookIdIsRequired                        = "Book ID is required"
	PositionAlreadyOccupied                 = "Position already occupied"
	BookNotInStore                          = "Book is not present in the store"
	FailedToStoreBook                       = "Failed to store the book"
	BookNotFoundAtSpecifiedPosition         = "Book not found at the specified position"
	FailedToRetrieveBookPosition            = "Failed to retrieve book position"
	LibraryUpdateFailure                    = "Failed to update the library"
)
